defmodule Credence.PriorArtDocTest do
  use ExUnit.Case, async: true

  @doc_path Path.expand("../docs/research/prior-art.md", __DIR__)

  test "the overview describes corpus validation as a snapshot ratchet" do
    [overview] =
      @doc_path
      |> File.read!()
      |> String.split("\n\n")
      |> Enum.filter(&String.starts_with?(&1, "Research report on techniques"))

    assert overview ==
             "Research report on techniques to raise the **precision, generality, safety, and non-redundancy**\n" <>
               "of auto-generated Elixir auto-fix rules. Credence's shape: AST pattern-match rules with source\n" <>
               "patches, every rule must auto-fix, validated by a corpus findings snapshot ratchet, generated by an LLM\n" <>
               "harness (weak model → clumsy solution → classifier extracts before/after anti-pattern → novelty\n" <>
               "check → equivalence check → agent implements rule+tests → gate: new-test + mutation + suite +\n" <>
               "corpus)."
  end

  test "the Alive2 recommendation preserves every admitted input" do
    [recommendation] =
      @doc_path
      |> File.read!()
      |> String.split("\n\n")
      |> Enum.filter(&String.starts_with?(&1, "**→** Two transferable ideas:"))

    assert recommendation ==
             "**→** Two transferable ideas: (1) Alive2's refinement model is not Credence's fix contract:\n" <>
               "a Credence fix must give exactly the same answer for every admitted input. Any rewrite that changes\n" <>
               "undefined or edge behavior must first narrow its guard so those inputs are not admitted, with that\n" <>
               "safety assumption declared and tested. (2) Prefer a checker that is sound-for-rejection (no false\n" <>
               "\"equivalent\") even if incomplete (may say \"unknown\"), matching Credence's corpus-ratchet posture."
  end
end
